apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-test
  namespace: disttaskqueue
spec:
  scaleTargetRef:
    name: worker-test
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: redis
      metadata:
        address: redis.disttaskqueue.svc.cluster.local:6379
        listName: queue:test
        listLength: "25"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-fetch
  namespace: disttaskqueue
spec:
  scaleTargetRef:
    name: worker-fetch
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: redis
      metadata:
        address: redis.disttaskqueue.svc.cluster.local:6379
        listName: queue:fetch
        listLength: "25"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-render
  namespace: disttaskqueue
spec:
  scaleTargetRef:
    name: worker-render
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: redis
      metadata:
        address: redis.disttaskqueue.svc.cluster.local:6379
        listName: queue:render
        listLength: "25"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-upload
  namespace: disttaskqueue
spec:
  scaleTargetRef:
    name: worker-upload
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 60
  triggers:
    - type: redis
      metadata:
        address: redis.disttaskqueue.svc.cluster.local:6379
        listName: queue:upload
        listLength: "25"
